### ISSUE TITLE
clarification on these settings...

### ISSUE THREAD

**Issue by eformx** [lowfuel/progrockdiffusion#120]
Just wondering what these do.  There is no mention in settings.md and nothing online that I have been able to find.  Are they old settings left in just to make things still run :) or are people using them to adjust contrast/brightness in the results? Or are these your special prog rock features?

    "fix_brightness_contrast": true,
    "high_contrast_threshold": 80,
    "high_contrast_adjust_amount": 0.85,
    "high_contrast_start": 20,
    "high_contrast_adjust": true,
    "low_contrast_threshold": 20,
    "low_contrast_adjust_amount": 2,
    "low_contrast_start": 20,
    "low_contrast_adjust": true,
    "high_brightness_threshold": 180,
    "high_brightness_adjust_amount": 0.85,
    "high_brightness_start": 0,
    "high_brightness_adjust": true,
    "low_brightness_threshold": 40,
    "low_brightness_adjust_amount": 1.15,
    "low_brightness_start": 0,
    "low_brightness_adjust": true,

**Comment by lowfuel** [comment]
Funny, I was just thinking about removing those. 
The only one you really need to worry about is the first one, which is simply saying if you want PRD to try to automatically keep brightness and contrast under control during a render. This can be very handy, and has saved a ton of images for me, but some people prefer to turn it off because they'd rather address such issues by improving their settings (totally understandable). 

The rest of the settings there basically control how fix_brightness_contrast behaves. I've never touched any of them, hence me thinking perhaps it would be best to remove them and simplify the settings files. 
The specifics of how they work I haven't explored. The fix_brightness_contrast mechanism was added by someone else and I never felt the need to really dive in and tweak it because it works so well with the defaults.

**Comment by eformx** [comment]
Thanks!  Just a thought, you might want to add some labels so we can mark things as Enhancement, Issue. As not everything is an issue :)

**Comment by lowfuel** [comment]
That's beyond my github skill -- how do I do that? :D

**Comment by eformx** [comment]
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels
