### ISSUE TITLE
Setup static checks

### ISSUE THREAD

**Issue by roma-glushko** [lowfuel/progrockdiffusion#13]
We can make a little code clean up if we integrate with some popular static check tools that could make sure our codebase is compatible with Python best practices and recommendations. Here is a few tools we can setup:

- isort
- flake8
- black

**Comment by lowfuel** [comment]
Let me think about that. The concern I have is that most of the code is straight from Disco Diffusion, and my hope has been to keep all that as close to the original as possible so that future updates to Disco aren't too hard to integrate. 

But after trying to integrate Disco v5 yesterday I fear we have already diverged too much for that goal to matter. It might be easier / better to simply evaluate new features added to Disco and bring them over in a sensible way?

I'm still on the fence. If we decide to go farther in modifying/improving the Disco codebase I am all for your suggestion, and in fact would love to go through and really clean out all of the iPython Widgets and Jupyter Notebook stuff that we don't need in there, but again, I've been reluctant to bother as it starts to stray too far from the source.

**Comment by roma-glushko** [comment]
@lowfuel yeah, completely understand that. On the bright side, the static checkers should not make the code base to differ a lot from the original code. After all it's all about using the consistent quotes, whitespaces and stuff like that. That said, I understand that diverging from the original code would mean harder the upgrade process.

**Comment by lowfuel** [comment]
> @lowfuel yeah, completely understand that. On the bright side, the static checkers should not make the code base to differ a lot from the original code. After all it's all about using the consistent quotes, whitespaces and stuff like that. That said, I understand that diverging from the original code would mean harder the upgrade process.

I hear ya. Love the idea in principal, but if it makes every line show up as different in a compare to Disco I would be sad. :)

**Comment by lowfuel** [comment]
Planning to move over to a totally new, streamlined, and extensible code base later this summer. Will revisit this topic after that if it's still a concern.
