### ISSUE TITLE
File name limitation

### ISSUE THREAD

**Issue by hydropix** [lowfuel/progrockdiffusion#31]
BatchNnum seems to be limited to 100 and replaces the new results.

**Comment by lowfuel** [comment]
What OS are you on? I've got folders with 300+ batchNum but it might be an OS specific problem?

There is a flaw in the logic, though, which is more likely the problem here. Did you remove any files from the directory? Disco's scheme works by counting the number of .json files in the directory, so if there are 99 then it will use 100 for the next batch, however if you removed a file in there that means there's already a file with 100 in the name even though there's only 99 files, so it uses 100 and 100 gets overwritten. That will continue happening essentially endlessly.

**Comment by lowfuel** [comment]
Let me see if I can improve the logic so it uses the highest numbered file + 1 as its starting point, rather than counting the number of files.

**Comment by hydropix** [comment]
I'm on Windows 10, I was testing the gobig option, maybe it's coming from there? The folder contains several files "Default_final_output_". And it would be a coincidence that the number stopped at 100?

**Comment by hydropix** [comment]
![image](https://user-images.githubusercontent.com/5154373/167722191-d6c35adb-5ad8-4929-b892-2184e3cebd35.png)

**Comment by lowfuel** [comment]
Nah those wouldn't effect it, it was just counting the number of files ending in .json, so my guess is there were 99 of those files but the numbering was off and the last one was called 100. 
I've fixed the logic to take the highest numbered json file and add 1, I think that will take care of it.
