### ISSUE TITLE
Error when building docker image

### ISSUE THREAD

**Issue by hwharrison** [lowfuel/progrockdiffusion#54]
I'm having trouble getting the docker image to build. It reaches the last step runs prd.py, and loads the model, but uses the CPU instead of the GPU. When I set the step size low so it'll get through that, it errors out with

`#12 260.9 Starting Run: Default(0) at frame 0
#12 260.9 Traceback (most recent call last):
#12 260.9   File "prd.py", line 2960, in <module>
#12 260.9     val = int(val_interpolate(1, int(cut_ic_pow), 1000, int(cut_ic_pow_final), i))
#12 260.9 ValueError: invalid literal for int() with base 10: 'None'`

I'm surprised even got that far with only the GPU pytorch libs, but I can't get it to use the GPU during the build process.

**Comment by lowfuel** [comment]
I'll be 100% honest here:

- Someone else created the docker file a while back.
- I'm not even sure if it was in working state back then as I have no idea how to use/test it, but they said it was working
- It's likely very out of date now, but, again, I don't know how to use or test it. I don't have any docker knowledge.

Personally I would rather remove it from the repo than try to fix it, as I really don't want to spend time learning docker just to validate the fixes and keep it up to date in the future. I probably shouldn't have accepted the merge request back then, but I was new to all this and didn't really know what I was getting into.

For the short term, if you (or someone else here) is knowledgeable about Docker and can try to figure out the issue, I would greatly appreciate it. Otherwise I'm afraid my answer is probably to remove the file.

Off the top of my head: I know it's very common to get torch problems if things aren't installed in just the right order. Several of the modules that get pulled in also pull in torch, and often (for whatever reason) they install the basic CPU version of torch, which is why torch gets reinstalled with the proper version at the end of the manual process. So it could be an order of operations thing in the docker file.

The other issue sounds like perhaps the Docker file is not installing the JSON5 module.

**Comment by lowfuel** [comment]
I should add - you can get around that last error by setting cut_it_pow_final to some value (2, let's say) in the settings file.

**Comment by rethinkwebdev** [comment]
This commit assumes cut_ic_pow_final is an INT and its set to 'none' 

Dockerfile has been working great for me otherwise!

https://github.com/lowfuel/progrockdiffusion/commit/048d48f94a74fba4fbf17c7683f1e953f2894c36

**Comment by rethinkwebdev** [comment]
> I should add - you can get around that last error by setting cut_it_pow_final to some value (2, let's say) in the settings file.

This didn't work. I had to revert to your commits from Sunday to get it to build

**Comment by lowfuel** [comment]
> This commit assumes cut_ic_pow_final is an INT and its set to 'none'
> 
> Dockerfile has been working great for me otherwise!
> 
> [048d48f](https://github.com/lowfuel/progrockdiffusion/commit/048d48f94a74fba4fbf17c7683f1e953f2894c36)

Okay, thanks. I will have a look tomorrow.

**Comment by lowfuel** [comment]
I think the cut_ic_pow_final issue should be resolved with last night's checkin, but I still don't know how to test and resolve the cuda problem.

**Comment by lowfuel** [comment]
Okay, I made a few tweaks to the docker file if one of you wants to help validate it. I was able to build the image on my mac, but that doesn't have an nvidia gpu so I don't know if it's fully working.

One of the tweaks I made was to run the prd.py command at the end with a different settings file called validate, which does just 10 steps with only one model turned on, which should render fairly quickly even on CPU. 

Note: I did get a error with the pytorch install command that's in there, which meant it fell back to using the pytorch that was installed by an earlier step in the process. That might be why it is using CPU for some of you.

If you see that error, you can try updating your dockerfile to use this command for installing pytorch (instead of the 3 commands that are in there now), and let me know if it works. If so I will update the dockerfile with this.

`    pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 --no-cache && \
`

**Comment by kjhenner** [comment]
I'm on Ubuntu with an nvidia gpu. I'll see if I can test this.

**Comment by hwharrison** [comment]
The cut_ic_pow_final issue is fixed, thank you!

I tested the single liner torch install. Pip prioritizes PyPI over extra-index-url, so it decides torch is already installed and keeps the CPU version. I was able to get the GPU version by installing torchvision before torch, avoiding the dependency error:

```
RUN echo "!! install torch, torchvision, torchaudio, imagemagic, ffmpeg, misc" && \
    pip install torchvision==0.11.3+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html && \
    pip install torch==1.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html --no-cache && \
    pip install torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html && \
```

It still doesn't use the GPU, but now it's because torch isn't detecting a cuda device. I believe this is because docker build doesn't expose GPUs, but I'm admittedly no Docker wizard either and so far I haven't been able to get it to pass in GPUs or run the container. Could be my setup. I have been using the native version instead and that's working great.

**Comment by kjhenner** [comment]
I've gotten Docker to use GPUs in the past, but it was a bit of a pain. If Docker support is important to folks, I could probably find some time to look into this.

Also, I'm wondering if it's important to have everything baked into the docker image. It could make the image a ton lighter and potentially easier to work with if we just mount the local directory for the models and code. Any thoughts on that?

**Comment by lowfuel** [comment]
I know very little about Docker, but I think the GPU needs to be specifically enabled when deploying the image. Is it possible that it won't work during the build of the image, but will if deployed properly after that?

As for baking things into the image, I will let others comment, but the use case for me is renting a powerful machine from vast.ai (or similar), and if I can pick a ProgRockDiffusion vm instead of a basic linux one, then I simply have to wait for the VM to come up and I'm ready to start rendering, which I think would be quite nice. In this scenario I don't have a persistent file system I can mount, it's a bring-up-then-destroy type arrangement.

A middle ground, though, is having the software installed but no models downloaded. We don't have to have those baked in, as they will download automatically the first time PRD runs. It's nice to run it for validation during the Docker build process itself, but maybe not necessary - as long as the image is tested by someone after its made, there's no real need to do it when its built.

Thoughts?

**Comment by kjhenner** [comment]
When you say VM, do you mean docker image, or does vast.ai need a VMI for a full VM? Both are doable. I'm just not familiar with vast.ai, so I have no idea what their options or interface are like.

But yeah, that all makes sense, otherwise! I'm used to using docker for testing and such during development, so it's nice to be able to link code and models in that context so you can edit on the fly. I think we easily could do both, though. Like have the latest code pre-loaded and just set an environment variable to point that directory so we could always have the option to link a local directory and specify it with that env variable when running the container.

**Comment by lowfuel** [comment]
Sorry, old habit - I mean docker image.

**Comment by kjhenner** [comment]
I got the docker image running running locally with access to my GPU. I'm on Ubuntu 20.04. YMMV with other systems, but at least this is a proof-of-concept.

I had to

- Update my nvidia drivers to 515
- Install the nvidia container toolkit: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html
- Run the container with the `--gpus all` flag, like: `sudo docker run --gpus all --env -it --name prd progrockdiffusion bash'

**Comment by lowfuel** [comment]
Just to confirm, is that with an image built with the current dockerfile?

**Comment by kjhenner** [comment]
I disabled the last run line that loads the models, but otherwise the same.

**Comment by lowfuel** [comment]
Excellent. Thanks. Going to close this for now.
