### ISSUE TITLE
Contribution suggestions?

### ISSUE THREAD

**Issue by kjhenner** [lowfuel/progrockdiffusion#55]
I've been really enjoying this project and would love to contribute! I know my way around python and pytorch pretty well, so hopefully I can bring some value. Any suggestions for places I might start?

Considering the code is adapted from the notebook, it seems like there's a lot of potential improvements to be made just in terms of code structure and organization. But probably "hey, let me come in and re-organize the whole code base" isn't a great way to get started! If there are any ideas about incremental places to start there I'd be happy to follow that guidance.

There are also some relatively low-hanging fruit for features I'd be interesting in contributing, especially around parameters and parameter control. Would be amazing, for example, to be able to schedule more params across the run, so we could ramp down the clip_guidance_scale, for example.

**Comment by lowfuel** [comment]
Hey, thanks for reaching out! Much appreciated. 

There's already an effort underway to completely revamp the code structure and organization, and it's quite far along and very impressive. It's being undertaken by @JrFolk. I'm not sure if he's ready for contributors to help out yet. Definitely best to help out there if that interests you, rather than re-inventing the wheel.

In terms of PRD in its current form, I'm no longer as worried about keeping the code base similar to the original notebook. At first I didn't want to stray to far so that new features in Disco could be added here easily, but as I've learned more about how it all works that issue hasn't really come up, in fact most of the new features in Disco have been added here first. All of which is to say, I'm totally on board with new features, etc.

My only main concern at this point is making sure existing PRD settings files continue to work as new versions are rolled out. As much as I'd love to re-do how parameters are set, stored, and used, I don't want to pull the rug out from under existing users. :)

Some things that come to mind:

- Absolutely on board with having more fun with parameter scheduling (either by the cut_overview style, or by linear interpolation, or other methods that aren't in there yet), and looking into which parameters can support that. For example I suspect prompt weights could change over the course of the render, which might be interesting (bring in those fine detail aspects more as you get towards the end of the image). 
- There are modules from the original notebook that we don't need, like the iPython Widgets and Jupyter stuff. I think these libraries are still included, but are not necessary, so can probably be ripped out. There are likely other things, too.
- Not sure how deep your pytorch knowledge is, but I would love to discuss ways things might be optimized. I know there are a variety of methods for speeding up pytorch, but they require much deeper knowledge of how it all works than I have.
- As an aside I'm also trying to get things working on the Apple M1 GPU using the latest pytorch nightly, but it seems that is still an incomplete pytorch implementation and does not yet have the things we need. Not sure if that is of any interest.
- One idea that came up recently was better handling of out-of-memory errors. If we can trap these and then perhaps have a rule set we follow to try and draw back settings automatically, then restart the render until it works. Ideally output "here's the settings that worked for your gpu" at the end. Probably an optional thing, but maybe on by default? Or a first-run scenario to setup for the user's GPU. I haven't really thought it through but it intrigued me
- I toyed around a while back with a more streamlined and easy install process in the branch simple-install, but got distracted and never finished it. Essentially I'd love to pair things down to a command or two, and have separate instructions per platform rather than everything mixed together. 
- There is a gui someone made, but it is really just a progress display, and also it requires pyqt5 which I can't even get to install properly. I wonder if this could be converted to tkinter so no additional installations are required, and perhaps made more useful (or at least more interesting). This has been very low on my list because, as a CLI app first and foremost, a gui isn't really needed. However it bothers me a bit that it's just sitting there and kind of languishing. :)

I'm open go other suggestions, too. Let me know what you think!

**Comment by kjhenner** [comment]
Awesome! Thanks for the thorough response!

If there's also some work on re-organization, it'll probably make sense to hold off on cleanup until after that's settled. I'll use that as an excuse to get into some fun stuff. I'll take a look at the code with an eye for optimization and memory efficiency and see if there's any low-hanging fruit there first, then play with parameter scheduling.

Regarding out of memory errors, it could be hard to have intelligent scaling there in a way that matches user preferences. Do we scale down the image size, change the cut schedule, turn off models? Maybe a good first step is just some kind of better accounting of memory usage, then at least a user knows what to change.

I personally found the installation very straight-forward and well-documented! Could always be improved, I'm sure, but that's my feedback for what it's worth. :)

**Comment by lowfuel** [comment]
Appreciate that!

Yes, good point about the out-of-memory. I'll think about that one more. Some profiling and general suggestions might be the best place to start.

`I'll take a look at the code with an eye for optimization and memory efficiency and see if there's any low-hanging fruit there first, then play with parameter scheduling.`

Sounds great!
