### ISSUE TITLE
how do I upscale something I like?

### ISSUE THREAD

**Issue by nikocraft** [lowfuel/progrockdiffusion#77]
Do I use gobig_scale? How does that work, what values should I use? Hope to get some clearance how to upscale images to higher res :)

**Comment by lowfuel** [comment]
If you have an existing you want to scale, you can run the same prd command used to create it, but add these options:
```
--gobig --gobiginit "some_directory/image.png"
```
(obvs change the part in quotes to whatever image you want)

This will scale it 2x. If you want to go even bigger than that, you can add gobig_scale to your settings file and set it to 3, 4, 5, whatever... but I *strongly* recommend not going over 3. It takes too long, for one thing, and the results are often mediocre due to the extremely tall and thin slices being rendered.

I also suggest alternatively that you look into a separate AI upscaler like Real-ESRGAN
https://github.com/xinntao/Real-ESRGAN

(note: if you have this installed and in your path you can trigger it directly from prd by adding the --esrgan command line option.)

It is much faster than the gobig method. Stylistically the results are different, so worth trying to see if it suits your need better. I know several users actually use a process like this:

- render an image with prd
- use go_big to double the size
- use esrgan (separately) to double the size again (or some other tool like gigapixel)

Thus going from an original 1024x768 image up to a full 4k image.

**Comment by nikocraft** [comment]
Jason, what can I do about this error? Did I miss to install something?

![image](https://user-images.githubusercontent.com/443080/175795339-c9ea61d6-9d5c-4311-b819-dd5b35cb7320.png)

![image](https://user-images.githubusercontent.com/443080/175795348-64cf1672-3773-441d-8e9f-7ab12c81c71a.png)

**Comment by lowfuel** [comment]
Oh - did you update prd today? I just checked in a big overhaul that might have already fixed this. Give it a try and let me know?

**Comment by lowfuel** [comment]
I see why it happened - there's no prompt for some reason. Can you post the prompt part of the settings? I may have broken something...

**Comment by lowfuel** [comment]
Okay I think I've checked in a fix for this (so many variations to test!). However please note that prompt switching (as seen in the change_prompt_sample.json file) is currently broken. But at least it won't crash -- it just only uses the first prompt. 
I'll try to sort that out tomorrow.

**Comment by nikocraft** [comment]
I think I now understand what happened. See line 4 :) I cleaned up that prompt because I was using your idea with powershell and prompts.txt to execute variations I want to test. I did not expect that prompt is needed to do an upscale of existing image. I'll pull the latest changes you did and test everything :)
![image](https://user-images.githubusercontent.com/443080/175811925-869b3c30-5126-4255-ba80-71fe48a1666c.png)

**Comment by lowfuel** [comment]
Ahhh yeah, sorry. It still uses the prompt to figure out what detail to add during the upscaling renders. It's not just an image resize, it actually re-runs the image through the system and adds more detail as it goes. The somewhat interesting side-effect from that is that you don't need to use the same prompt as the original render. So you could, in theory, use a prompt that is much more focused on detail stuff. Play around with it. :)

**Comment by lowfuel** [comment]
Fixed a few more bugs just now related to prompts, by the way. I think it's all working.
